# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie
from .scrollableLabel import ScrollableLabel


class LoadingScreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setStyleSheet("background-color: rgb(0, 8, 20);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lStatus = QtWidgets.QLabel(self.centralwidget)
        self.lStatus.setGeometry(QtCore.QRect(415, 60, 451, 40))
        self.lStatus.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "font: 24pt \"MS Shell Dlg 2\";")
        self.lStatus.setObjectName("lStatus")
        self.lAnim = QtWidgets.QLabel(self.centralwidget)
        self.lAnim.setGeometry(QtCore.QRect(440, 160, 400, 400))
        self.lAnim.setText("")
        self.lAnim.setObjectName("lAnim")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(0, 0, 90, 40))
        self.btnCancel.setStyleSheet("background-color: rgb(0, 29, 61);\n"
                                     "border: 1px solid rgb(255, 195, 0);\n"
                                     "color: rgb(255, 195, 0);\n"
                                     "font: 20pt \"MS Shell Dlg 2\";")
        self.btnCancel.setObjectName("btnCancel")
        self.scrollableLabel = ScrollableLabel(parent=self.centralwidget)

        # self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollableLabel.setGeometry(QtCore.QRect(970, 400, 300, 300))
        self.scrollableLabel.setWidgetResizable(True)
        self.scrollableLabel.setObjectName("scrollableLabel")
        # self.scrollAreaWidgetContents = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 298, 298))
        # self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.movie = QMovie("../resource/loading.gif")
        self.movie.setScaledSize(QtCore.QSize(400, 400))
        self.lAnim.setMovie(self.movie)

        self.startAnimation()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Video Stabilization Project"))
        self.lStatus.setText(_translate("MainWindow", "Your video is being processed..."))
        self.btnCancel.setText(_translate("MainWindow", "Cancel"))

    def startAnimation(self):
        self.movie.start()

    # Stop Animation(According to need)
    def stopAnimation(self):
        self.movie.stop()

    def appendText(self, text):
        self.scrollableLabel.appendText(text)

